# Generated by Django 3.1 on 2020-09-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='full_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='urlentry',
            name='url_hash',
            field=models.TextField(),
        ),
    ]
